# Generated by Django 4.1 on 2022-09-08 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatroom', '0008_remove_message_read_readmessages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readmessages',
            options={'verbose_name': 'Прочитанное сообщение', 'verbose_name_plural': 'Прочитанные сообщения'},
        ),
        migrations.AlterField(
            model_name='readmessages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
