# Generated by Django 4.1 on 2022-09-08 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatroom', '0010_alter_readmessages_message_alter_readmessages_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readmessages',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatroom.message'),
        ),
        migrations.AlterField(
            model_name='readmessages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
