# Generated by Django 4.1 on 2022-09-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0015_alter_message_options_userlogo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlogo',
            options={'verbose_name': 'Логотип пользователя', 'verbose_name_plural': 'Логотипы пользователей'},
        ),
    ]
