# Generated by Django 4.1 on 2022-09-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0019_usertimeonline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertimeonline',
            options={'ordering': ['-time_online'], 'verbose_name': 'Пользователь онлайн', 'verbose_name_plural': 'Пользователи онлайн'},
        ),
    ]
